#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"
export PYTHONPATH="$ROOT_DIR:${PYTHONPATH:-}"

# Avoid OpenBLAS oversubscription / NUM_THREADS crashes on many-core servers.
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-32}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-32}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-32}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-32}"
source "$SCRIPT_DIR/_argparse.sh" "$@"

# Run exactly one social experiment by default to avoid long blocking jobs.
# Available exp_id values:
#   prototype_response, style_shift, exposure_response, lead_lag,
#   user_heterogeneity, channel_migration/channel_style, all
#
# NOTE: prototype_response is now a backward-compatible name for Task 1:
#   axis-level COVID style shift with calendar-matched YoY de-seasonalization.
# Routed prompt prototypes are treated only as intermediate knowledge injection,
# not as the social-analysis unit.
DEFAULT_AXIS_DIMS="formality_structure,public_private_occasion,comfort_ease,practical_value,trend_expressiveness,material_softness,material_thermal_weight,material_durability,color_temperature,color_lightness,color_chroma,design_complexity,fit_looseness,office_like,homewear_like,casual_like,social_outing_like,value_basic"
DEFAULT_TASK1_RAW_AXIS_DIMS="formality_structure,public_private_occasion,comfort_ease,practical_value,trend_expressiveness,design_complexity,fit_looseness"
DEFAULT_TASK1_COMPOSITE_DIMS="office_like,homewear_like,casual_like,social_outing_like,value_basic"
DEFAULT_TASK1_AXIS_DIMS="$DEFAULT_TASK1_RAW_AXIS_DIMS,$DEFAULT_TASK1_COMPOSITE_DIMS"
DEFAULT_TASK1_SEASON_DIMS="material_thermal_weight,color_temperature,color_lightness,material_softness"

CMD=(python -m util.social_analysis
  --exp_id "${exp_id:-prototype_response}"
  --exp_name "${exp_name:-}"
  --social_output_root "${social_output_root:-./social_output/k}"
  --data_root "${data_root:-./data}"
  --event_month "${event_month:-2020-03}"
  --style_dims "${style_dims:-$DEFAULT_AXIS_DIMS}"
  --task1_axis_dims "${task1_axis_dims:-$DEFAULT_TASK1_AXIS_DIMS}"
  --task1_raw_axis_dims "${task1_raw_axis_dims:-$DEFAULT_TASK1_RAW_AXIS_DIMS}"
  --task1_composite_dims "${task1_composite_dims:-$DEFAULT_TASK1_COMPOSITE_DIMS}"
  --task1_pca_dims "${task1_pca_dims:-$DEFAULT_TASK1_RAW_AXIS_DIMS}"
  --task1_copula_dims "${task1_copula_dims:-$DEFAULT_TASK1_RAW_AXIS_DIMS}"
  --task1_season_control_dims "${task1_season_control_dims:-$DEFAULT_TASK1_SEASON_DIMS}"
  --task1_covid_end_month "${task1_covid_end_month:-}"
  --task1_bootstrap_n "${task1_bootstrap_n:-500}"
  --task1_category_residualize "${task1_category_residualize:-1}"
  --task1_residual_max_cat_levels "${task1_residual_max_cat_levels:-60}"
  --primary_covid_var "${primary_covid_var:-covid_cases_index}"
  --make_figures "${make_figures:-1}"
  --seed "${seed:-42}"
  --min_periods "${min_periods:-8}"
  --top_n "${top_n:-30}"
  --outlier_z_bound "${outlier_z_bound:-2.5}"
  --num_clusters "${num_clusters:-4}"
  --prototype_fallback_from_scores "${prototype_fallback_from_scores:-0}"
  --prototype_high_quantile "${prototype_high_quantile:-0.75}"
  --prototype_low_quantile "${prototype_low_quantile:-0.25}"
  --prototype_p_clip_min "${prototype_p_clip_min:-1e-16}"
  --prototype_volcano_label_n "${prototype_volcano_label_n:-12}"
  --hist_bins "${hist_bins:-30}"
  --max_samples "${max_samples:-50000}"
  --exposure_dims "${exposure_dims:-formality_structure,comfort_ease,homewear_like,office_like}"
  --high_quantile "${high_quantile:-0.75}"
  --low_quantile "${low_quantile:-0.25}"
  --event_window "${event_window:-8}"
  --max_lead "${max_lead:-2}"
  --max_lag "${max_lag:-4}"
  --run_ardl "${run_ardl:-1}"
  --ar_lags "${ar_lags:-2}"
  --covid_csv "${covid_csv:-}"
  --covid_location "${covid_location:-World}"
  --lead_lag_start_date "${lead_lag_start_date:-2019-10-01}"
  --lead_lag_end_date "${lead_lag_end_date:-2020-09-30}"
  --lead_lag_dims "${lead_lag_dims:-comfort_ease,homewear_like,fit_looseness,value_basic,office_like,public_private_occasion,social_outing_like,trend_expressiveness,design_complexity,formality_structure,practical_value}"
  --lead_lag_season_control_dims "${lead_lag_season_control_dims:-$DEFAULT_TASK1_SEASON_DIMS}"
  --lead_lag_covid_vars "${lead_lag_covid_vars:-covid_cases_index,covid_deaths_index,covid_reproduction_rate,covid_stringency_index}"
  --lead_lag_covid_transform "${lead_lag_covid_transform:-delta7}"
  --lead_lag_roll_days "${lead_lag_roll_days:-7}"
  --lead_lag_max_lag_days "${lead_lag_max_lag_days:-28}"
  --lead_lag_placebo_days "${lead_lag_placebo_days:-7}"
  --lead_lag_bins "${lead_lag_bins:-0:3,4:7,8:14,15:28}"
  --lead_lag_prewhiten_lags "${lead_lag_prewhiten_lags:-7}"
  --lead_lag_ar_lags_daily "${lead_lag_ar_lags_daily:-7}"
  --lead_lag_hac_lags_daily "${lead_lag_hac_lags_daily:-7}"
  --lead_lag_residualize_dow "${lead_lag_residualize_dow:-1}"
  --lead_lag_residualize_trend "${lead_lag_residualize_trend:-1}"
  --lead_lag_residualize_season_axes "${lead_lag_residualize_season_axes:-1}"
  --lead_lag_control_transactions "${lead_lag_control_transactions:-1}"
  --max_purchase_rows "${max_purchase_rows:-0}"
  --min_age "${min_age:-16}"
  --max_age "${max_age:-80}"
  --age_bin_width "${age_bin_width:-2}"
  --gmm_components "${gmm_components:-3}"
  --gmm_sample_size "${gmm_sample_size:-30000}"
  --user_axis_dims "${user_axis_dims:-comfort_ease,homewear_like,fit_looseness,value_basic,office_like,public_private_occasion,social_outing_like,trend_expressiveness,design_complexity,formality_structure,practical_value}"
  --user_kde_dims "${user_kde_dims:-comfort_ease,office_like,trend_expressiveness,value_basic,homewear_like,public_private_occasion}"
  --user_season_control_dims "${user_season_control_dims:-$DEFAULT_TASK1_SEASON_DIMS}"
  --user_group_fields "${user_group_fields:-age_group,club_member_status,fashion_news_frequency}"
  --user_covid_end_month "${user_covid_end_month:-${task1_covid_end_month:-}}"
  --user_use_cuda "${user_use_cuda:-auto}"
  --user_txn_weighting "${user_txn_weighting:-user_balanced}"
  --user_run_transaction_kde "${user_run_transaction_kde:-1}"
  --user_run_transaction_gmm "${user_run_transaction_gmm:-1}"
  --user_run_user_gmm "${user_run_user_gmm:-1}"
  --user_kde_age_bins "${user_kde_age_bins:-65}"
  --user_kde_score_bins "${user_kde_score_bins:-60}"
  --user_kde_bandwidth_age "${user_kde_bandwidth_age:-2.5}"
  --user_kde_bandwidth_score "${user_kde_bandwidth_score:-0.035}"
  --user_gmm_iter "${user_gmm_iter:-80}"
  --channel_axis_dims "${channel_axis_dims:-comfort_ease,homewear_like,fit_looseness,value_basic,office_like,public_private_occasion,social_outing_like,trend_expressiveness,design_complexity,formality_structure,practical_value}"
  --channel_decomposition_dims "${channel_decomposition_dims:-comfort_ease,homewear_like,fit_looseness,value_basic,office_like,public_private_occasion,social_outing_like,trend_expressiveness,design_complexity,formality_structure,practical_value}"
  --channel_plot_dims "${channel_plot_dims:-comfort_ease,homewear_like,office_like,public_private_occasion,trend_expressiveness,design_complexity}"
  --channel_covid_end_month "${channel_covid_end_month:-${task1_covid_end_month:-}}"
  --channel_fill_missing_channels "${channel_fill_missing_channels:-1}"
  --channel_plot_top_dims "${channel_plot_top_dims:-6}"
  --channel_target_id "${channel_target_id:-2}"
  --channel_start_date "${channel_start_date:-}"
  --channel_end_date "${channel_end_date:-}"
  --channel_regression_start_date "${channel_regression_start_date:-2019-10-01}"
  --channel_regression_end_date "${channel_regression_end_date:-2020-09-30}"
  --channel_exclude_months "${channel_exclude_months:-}"
  --channel_covid_vars "${channel_covid_vars:-covid_cases_index,covid_deaths_index,covid_reproduction_rate,covid_stringency_index}"
  --channel_covid_transform "${channel_covid_transform:-delta7}"
  --channel_lag_bins "${channel_lag_bins:-0:3,4:7,8:14,15:28}"
  --channel_hac_lags_daily "${channel_hac_lags_daily:-7}"
  --channel_min_daily_obs "${channel_min_daily_obs:-30}"
  --channel_logit_eps "${channel_logit_eps:-1e-4}"
  --channel_group_fields "${channel_group_fields:-age_group,club_member_status,fashion_news_frequency}"
  --channel_regression_lagged_share "${channel_regression_lagged_share:-1}"
  --channel_control_transactions "${channel_control_transactions:-1}"
  --channel_control_dow "${channel_control_dow:-1}"
  --channel_control_trend "${channel_control_trend:-1}"
)
"${CMD[@]}"
